In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/KEERTHANA/Downloads/student_dataset_10000_rows.CSV")

In [2]:
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [4]:
df.loc[df["attendance"]<75]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9990,4,72,8,6,4,72,86.47,Placed
9994,4,53,7,8,10,71,85.02,Placed
9995,2,58,9,7,8,88,69.31,Not Placed
9997,10,44,8,5,10,37,95.94,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [6]:
df.loc[(df["attendance"]>75)&(df["attendance"]<90)]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
7,3,86,7,3,7,85,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
16,3,76,8,10,6,36,63.26,Not Placed
17,6,80,8,10,11,47,91.89,Placed
20,8,88,7,4,14,67,100.00,Placed
...,...,...,...,...,...,...,...,...
9971,11,81,9,6,0,85,100.00,Placed
9975,10,76,6,3,5,66,93.79,Placed
9979,11,78,9,5,18,82,100.00,Placed
9985,8,89,9,3,12,68,100.00,Placed
9993,10,86,9,9,15,63,100.00,Placed

In [13]:
df.loc[df["placement_status"].str.contains("Not")]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
16,3,76,8,10,6,36,63.26,Not Placed
34,4,40,8,7,15,59,63.20,Not Placed
37,5,81,7,5,2,64,63.65,Not Placed
43,2,68,7,11,4,76,55.39,Not Placed
46,2,48,5,10,8,57,66.93,Not Placed
...,...,...,...,...,...,...,...,...
9963,4,94,5,7,9,39,59.82,Not Placed
9965,1,86,8,2,2,39,61.29,Not Placed
9981,1,53,5,6,12,56,69.62,Not Placed
9986,6,60,5,4,4,50,68.45,Not Placed
9995,2,58,9,7,8,88,69.31,Not Placed

In [14]:
df.loc[df["placement_status"].str.startswith("Not")]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
16,3,76,8,10,6,36,63.26,Not Placed
34,4,40,8,7,15,59,63.20,Not Placed
37,5,81,7,5,2,64,63.65,Not Placed
43,2,68,7,11,4,76,55.39,Not Placed
46,2,48,5,10,8,57,66.93,Not Placed
...,...,...,...,...,...,...,...,...
9963,4,94,5,7,9,39,59.82,Not Placed
9965,1,86,8,2,2,39,61.29,Not Placed
9981,1,53,5,6,12,56,69.62,Not Placed
9986,6,60,5,4,4,50,68.45,Not Placed
9995,2,58,9,7,8,88,69.31,Not Placed

In [16]:
df.loc[df["attendance"]<75,["grade"]]="Fail"

In [17]:
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,Fail
1,4,69,5,3,8,56,100.00,Placed,Fail
2,11,60,7,6,10,45,100.00,Placed,Fail
3,8,99,9,8,4,55,90.17,Placed,NaN
4,5,52,8,6,8,40,78.82,Placed,Fail
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,Fail
9996,7,98,6,9,4,87,100.00,Placed,NaN
9997,10,44,8,5,10,37,95.94,Placed,Fail
9998,10,75,7,5,8,52,88.61,Placed,NaN
9999,2,70,6,11,16,52,78.96,Placed,Fail

In [1]:
df.loc[df["percentage"]>=70,["grade"]]="High"

NameError: name 'df' is not defined