In [ ]:
import pandas

In [ ]:
import pandas as pd

In [ ]:
dataset=pd.read_csv("C:/Users\KEERTHANA/Downloads/student_dataset_10000_rows.csv")

In [ ]:
dataset.head(10)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
6,10,40,4,11,9,50,98.12,Placed
7,3,86,7,3,7,85,100.00,Placed
8,7,72,8,5,18,48,96.81,Placed
9,11,77,4,9,15,69,100.00,Placed

In [ ]:
dataset.tail(20)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9980,6,50,8,8,3,78,78.22,Placed
9981,1,53,5,6,12,56,69.62,Not Placed
9982,6,62,6,4,20,55,100.00,Placed
9983,6,92,6,10,18,62,83.24,Placed
9984,6,55,8,8,15,83,100.00,Placed
9985,8,89,9,3,12,68,100.00,Placed
9986,6,60,5,4,4,50,68.45,Not Placed
9987,5,94,7,11,11,45,86.61,Placed
9988,11,94,6,9,6,67,100.00,Placed
9989,2,43,7,5,8,78,100.00,Placed
9990,4,72,8,6,4,72,86.47,Placed
9991,10,93,7,11,3,53,97.90,Placed
9992,5,100,9,2,9,62,100.00,Placed
9993,10,86,9,9,15,63,100.00,Placed
9994,4,53,7,8,10,71,85.02,Placed
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
dataset.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [ ]:
dataset.shape

(10000, 8)

In [ ]:
dataset[0:6:2]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
4,5,52,8,6,8,40,78.82,Placed

In [ ]:
dataset[0:5:1]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [ ]:
dataset['attendance']

0       56
1       69
2       60
3       99
4       52
        ..
9995    58
9996    98
9997    44
9998    75
9999    70
Name: attendance, Length: 10000, dtype: int64

In [ ]:
dataset[["study_hours","attendance"]][0:10:1]

   study_hours  attendance
0            7          56
1            4          69
2           11          60
3            8          99
4            5          52
5            7          40
6           10          40
7            3          86
8            7          72
9           11          77

In [ ]:
for  rec in dataset.iterrows():
    print(rec)

(0, study_hours                   7
attendance                   56
sleep_hours                   8
internet_usage                7
assignments_completed        10
previous_score               62
exam_score                100.0
placement_status         Placed
Name: 0, dtype: object)
(1, study_hours                   4
attendance                   69
sleep_hours                   5
internet_usage                3
assignments_completed         8
previous_score               56
exam_score                100.0
placement_status         Placed
Name: 1, dtype: object)
(2, study_hours                  11
attendance                   60
sleep_hours                   7
internet_usage                6
assignments_completed        10
previous_score               45
exam_score                100.0
placement_status         Placed
Name: 2, dtype: object)
(3, study_hours                   8
attendance                   99
sleep_hours                   9
internet_usage                8
assignments_completed         4
previous_score               55
exam_score                90.17
placement_status         Placed
Name: 3, dtype: object)
(4, study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object)
(5, study_hours                   7
attendance                   40
sleep_hours                   9
internet_usage               10
assignments_completed         0
previous_score               60
exam_score                72.33
placement_status         Placed
Name: 5, dtype: object)
(6, study_hours                  10
attendance                   40
sleep_hours                   4
internet_usage               11
assignments_completed         9
previous_score               50
exam_score                98.12
placement_status         Placed
Name: 6, dtype: object)
(7, study_hours                   3
attendance                   86
sleep_hours                   7
internet_usage                3
assignments_completed         7
previous_score               85
exam_score                100.0
placement_status         Placed
Name: 7, dtype: object)
(8, study_hours                   7
attendance                   72
sleep_hours                   8
internet_usage                5
assignments_completed        18
previous_score               48
exam_score                96.81
placement_status         Placed
Name: 8, dtype: object)
(9, study_hours                  11
attendance                   77
sleep_hours                   4
internet_usage                9
assignments_completed        15
previous_score               69
exam_score                100.0
placement_status         Placed
Name: 9, dtype: object)
(10, study_hours                  11
attendance                   64
sleep_hours                   8
internet_usage                8
assignments_completed        12
previous_score               76
exam_score                100.0
placement_status         Placed
Name: 10, dtype: object)
(11, study_hours                   8
attendance                   65
sleep_hours                   5
internet_usage                6
assignments_completed         4
previous_score               87
exam_score                100.0
placement_status         Placed
Name: 11, dtype: object)
(12, study_hours                   5
attendance                   52
sleep_hours                   6
internet_usage                9
assignments_completed        17
previous_score               89
exam_score                95.36
placement_status         Placed
Name: 12, dtype: object)
(13, study_hours                   4
attendance                   98
sleep_hours                   9
internet_usage                2
assignments_completed         8
previous_score               70
exam_score                100.0
placement_status         Placed
Name: 13, dtype: object)
(14, study_hours                   8
attendance                   67
sleep_hours                   8
internet_usage               11
assignments_completed         3
previous_score               56
exam_score                83.49
placement_status         Placed
Name: 14, dtype: object)
(15, study_hours                   8
attendance                   72
sleep_hours                   7
internet_usage                9
assignments_completed        13
previous_score               87
exam_score                100.0
placement_status         Placed
Name: 15, dtype: object)
(16, study_hours                       3
attendance                       76
sleep_hours                       8
internet_usage                   10
assignments_completed             6
previous_score                   36
exam_score                    63.26
placement_status         Not Placed
Name: 16, dtype: object)
(17, study_hours                   6
attendance                   80
sleep_hours                   8
internet_usage               10
assignments_completed        11
previous_score               47
exam_score                91.89
placement_status         Placed
Name: 17, dtype: object)
(18, study_hours                   5
attendance                   69
sleep_hours                   8
internet_usage                6
assignments_completed         6
previous_score               45
exam_score                73.69
placement_status         Placed
Name: 18, dtype: object)
(19, study_hours                   2
attendance                   96
sleep_hours                   8
internet_usage                9
assignments_completed        10
previous_score               46
exam_score                77.59
placement_status         Placed
Name: 19, dtype: object)
(20, study_hours                   8
attendance                   88
sleep_hours                   7
internet_usage                4
assignments_completed        14
previous_score               67
exam_score                100.0
placement_status         Placed
Name: 20, dtype: object)
(21, study_hours                   6
attendance                   87
sleep_hours                   7
internet_usage                5
assignments_completed         6
previous_score               56
exam_score                77.19
placement_status         Placed
Name: 21, dtype: object)
(22, study_hours                   2
attendance                   47
sleep_hours                   8
internet_usage                2
assignments_completed        19
previous_score               87
exam_score                98.66
placement_status         Placed
Name: 22, dtype: object)
(23, study_hours                   5
attendance                   88
sleep_hours                   6
internet_usage                3
assignments_completed        16
previous_score               43
exam_score                100.0
placement_status         Placed
Name: 23, dtype: object)
(24, study_hours                   1
attendance                   86
sleep_hours                   8
internet_usage                1
assignments_completed         4
previous_score               78
exam_score                91.65
placement_status         Placed
Name: 24, dtype: object)
(25, study_hours                  10
attendance                   95
sleep_hours                   9
internet_usage                4
assignments_completed         7
previous_score               41
exam_score                100.0
placement_status         Placed
Name: 25, dtype: object)
(26, study_hours                   6
attendance                   40
sleep_hours                   9
internet_usage                2
assignments_completed         9
previous_score               51
exam_score                 95.6
placement_status         Placed
Name: 26, dtype: object)
(27, study_hours                   9
attendance                   51
sleep_hours                   7
internet_usage                2
assignments_completed         5
previous_score               95
exam_score                100.0
placement_status         Placed
Name: 27, dtype: object)
(28, study_hours                   1
attendance                   44
sleep_hours                   9
internet_usage                1
assignments_completed        20
previous_score               44
exam_score                76.12
placement_status         Placed
Name: 28, dtype: object)
(29, study_hours                  11
attendance                   63
sleep_hours                   9
internet_usage               10
assignments_completed         1
previous_score               72
exam_score                96.59
placement_status         Placed
Name: 29, dtype: object)
(30, study_hours                  11
attendance                   45
sleep_hours                   5
internet_usage                2
assignments_completed         4
previous_score               93
exam_score                100.0
placement_status         Placed
Name: 30, dtype: object)
(31, study_hours                  10
attendance                   64
sleep_hours                   8
internet_usage                4
assignments_completed         9
previous_score               73
exam_score                100.0
placement_status         Placed
Name: 31, dtype: object)
(32, study_hours                   3
attendance                   40
sleep_hours                   8
internet_usage                6
assignments_completed         2
previous_score               85
exam_score                75.73
placement_status         Placed
Name: 32, dtype: object)
(33, study_hours                   7
attendance                   64
sleep_hours                   8
internet_usage                7
assignments_completed        12
previous_score               80
exam_score                98.68
placement_status         Placed
Name: 33, dtype: object)
(34, study_hours                       4
attendance                       40
sleep_hours                       8
internet_usage                    7
assignments_completed            15
previous_score                   59
exam_score                     63.2
placement_status         Not Placed
Name: 34, dtype: object)
(35, study_hours                   9
attendance                   71
sleep_hours                   4
internet_usage                7
assignments_completed        14
previous_score               61
exam_score                100.0
placement_status         Placed
Name: 35, dtype: object)
(36, study_hours                   3
attendance                   81
sleep_hours                   8
internet_usage                4
assignments_completed         1
previous_score               64
exam_score                 79.7
placement_status         Placed
Name: 36, dtype: object)
(37, study_hours                       5
attendance                       81
sleep_hours                       7
internet_usage                    5
assignments_completed             2
previous_score                   64
exam_score                    63.65
placement_status         Not Placed
Name: 37, dtype: object)
(38, study_hours                   3
attendance                   42
sleep_hours                   7
internet_usage               11
assignments_completed        19
previous_score               77
exam_score                78.22
placement_status         Placed
Name: 38, dtype: object)
(39, study_hours                   7
attendance                   88
sleep_hours                   4
internet_usage                3
assignments_completed        17
previous_score               68
exam_score                100.0
placement_status         Placed
Name: 39, dtype: object)
(40, study_hours                   5
attendance                   58
sleep_hours                   8
internet_usage                1
assignments_completed        19
previous_score               67
exam_score                100.0
placement_status         Placed
Name: 40, dtype: object)
(41, study_hours                   9
attendance                   99
sleep_hours                   6
internet_usage                8
assignments_completed        19
previous_score               66
exam_score                100.0
placement_status         Placed
Name: 41, dtype: object)
(42, study_hours                   7
attendance                   82
sleep_hours                   8
internet_usage               10
assignments_completed        14
previous_score               92
exam_score                100.0
placement_status         Placed
Name: 42, dtype: object)
(43, study_hours                       2
attendance                       68
sleep_hours                       7
internet_usage                   11
assignments_completed             4
previous_score                   76
exam_score                    55.39
placement_status         Not Placed
Name: 43, dtype: object)
(44, study_hours                   4
attendance                   89
sleep_hours                   5
internet_usage                7
assignments_completed        10
previous_score               46
exam_score                90.41
placement_status         Placed
Name: 44, dtype: object)
(45, study_hours                   9
attendance                   41
sleep_hours                   9
internet_usage                9
assignments_completed         2
previous_score               75
exam_score                86.67
placement_status         Placed
Name: 45, dtype: object)
(46, study_hours                       2
attendance                       48
sleep_hours                       5
internet_usage                   10
assignments_completed             8
previous_score                   57
exam_score                    66.93
placement_status         Not Placed
Name: 46, dtype: object)
(47, study_hours                  10
attendance                   95
sleep_hours                   6
internet_usage                4
assignments_completed         6
previous_score               92
exam_score                100.0
placement_status         Placed
Name: 47, dtype: object)
(48, study_hours                   9
attendance                   56
sleep_hours                   8
internet_usage                5
assignments_completed         1
previous_score               63
exam_score                100.0
placement_status         Placed
Name: 48, dtype: object)
(49, study_hours                  10
attendance                   99
sleep_hours                   4
internet_usage                5
assignments_completed        14
previous_score               77
exam_score                100.0
placement_status         Placed
Name: 49, dtype: object)
(50, study_hours                   5
attendance                   85
sleep_hours                   8
internet_usage                7
assignments_completed        11
previous_score               35
exam_score                82.35
placement_status         Placed
Name: 50, dtype: object)
(51, study_hours                       2
attendance                       75
sleep_hours                       6
internet_usage                    9
assignments_completed            15
previous_score                   54
exam_score                    65.43
placement_status         Not Placed
Name: 51, dtype: object)
(52, study_hours                   4
attendance                  100
sleep_hours                   6
internet_usage                8
assignments_completed        15
previous_score               44
exam_score                100.0
placement_status         Placed
Name: 52, dtype: object)
(53, study_hours                   7
attendance                   56
sleep_hours                   9
internet_usage                7
assignments_completed        15
previous_score               95
exam_score                100.0
placement_status         Placed
Name: 53, dtype: object)
(54, study_hours                   8
attendance                   88
sleep_hours                   6
internet_usage                1
assignments_completed        18
previous_score               53
exam_score                100.0
placement_status         Placed
Name: 54, dtype: object)
(55, study_hours                   3
attendance                   51
sleep_hours                   5
internet_usage               10
assignments_completed         2
previous_score               93
exam_score                 81.7
placement_status         Placed
Name: 55, dtype: object)
(56, study_hours                   1
attendance                   99
sleep_hours                   9
internet_usage                6
assignments_completed        19
previous_score               57
exam_score                100.0
placement_status         Placed
Name: 56, dtype: object)
(57, study_hours                   4
attendance                   59
sleep_hours                   8
internet_usage               10
assignments_completed         3
previous_score               55
exam_score                80.04
placement_status         Placed
Name: 57, dtype: object)
(58, study_hours                       2
attendance                       89
sleep_hours                       8
internet_usage                    9
assignments_completed             0
previous_score                   91
exam_score                    69.17
placement_status         Not Placed
Name: 58, dtype: object)
(59, study_hours                   8
attendance                   42
sleep_hours                   4
internet_usage                7
assignments_completed         7
previous_score               77
exam_score                91.55
placement_status         Placed
Name: 59, dtype: object)
(60, study_hours                   4
attendance                   82
sleep_hours                   6
internet_usage                1
assignments_completed        14
previous_score               69
exam_score                100.0
placement_status         Placed
Name: 60, dtype: object)
(61, study_hours                   2
attendance                   96
sleep_hours                   6
internet_usage                9
assignments_completed        20
previous_score               93
exam_score                93.77
placement_status         Placed
Name: 61, dtype: object)
(62, study_hours                   6
attendance                   89
sleep_hours                   7
internet_usage                3
assignments_completed         4
previous_score               82
exam_score                100.0
placement_status         Placed
Name: 62, dtype: object)
(63, study_hours                   6
attendance                   43
sleep_hours                   9
internet_usage                9
assignments_completed        19
previous_score               66
exam_score                94.47
placement_status         Placed
Name: 63, dtype: object)
(64, study_hours                  10
attendance                   56
sleep_hours                   7
internet_usage                4
assignments_completed        11
previous_score               88
exam_score                100.0
placement_status         Placed
Name: 64, dtype: object)
(65, study_hours                   4
attendance                   89
sleep_hours                   9
internet_usage                9
assignments_completed        19
previous_score               44
exam_score                87.79
placement_status         Placed
Name: 65, dtype: object)
(66, study_hours                   6
attendance                   76
sleep_hours                   5
internet_usage                8
assignments_completed        19
previous_score               36
exam_score                94.36
placement_status         Placed
Name: 66, dtype: object)
(67, study_hours                   2
attendance                   85
sleep_hours                   9
internet_usage                7
assignments_completed         3
previous_score               85
exam_score                79.22
placement_status         Placed
Name: 67, dtype: object)
(68, study_hours                  10
attendance                   81
sleep_hours                   8
internet_usage                4
assignments_completed        14
previous_score               70
exam_score                100.0
placement_status         Placed
Name: 68, dtype: object)
(69, study_hours                   2

In [ ]:
dataset.loc[1]

study_hours                   4
attendance                   69
sleep_hours                   5
internet_usage                3
assignments_completed         8
previous_score               56
exam_score                100.0
placement_status         Placed
Name: 1, dtype: object

In [ ]:
dataset.loc[2,["attendance"]]

attendance    60
Name: 2, dtype: object

In [ ]:
dataset.loc[0:6]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed

In [ ]:
dataset.iloc[0:6]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed

In [ ]:
dataset.loc[0:5,["sleep_hours","attendance"]]

   sleep_hours  attendance
0            8          56
1            5          69
2            7          60
3            9          99
4            8          52
5            9          40

In [ ]:
dataset.loc[0:10,"sleep_hours":"attendance"]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:

dataset.iloc[2,4]

np.int64(10)

In [ ]:
dataset.iloc[0:8,0:6]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
0,7,56,8,7,10,62
1,4,69,5,3,8,56
2,11,60,7,6,10,45
3,8,99,9,8,4,55
4,5,52,8,6,8,40
5,7,40,9,10,0,60
6,10,40,4,11,9,50
7,3,86,7,3,7,85

In [ ]:
dataset.iloc[1:7,4]

1     8
2    10
3     4
4     8
5     0
6     9
Name: assignments_completed, dtype: int64

In [ ]:
dataset.iloc[1:10,[1,2]]

   attendance  sleep_hours
1          69            5
2          60            7
3          99            9
4          52            8
5          40            9
6          40            4
7          86            7
8          72            8
9          77            4