In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/KEERTHANA/Downloads/StudentGradesAndPrograms.csv")

C:\Users\KEERTHANA\AppData\Local\Temp\ipykernel_12716\741337720.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:/Users/KEERTHANA/Downloads/StudentGradesAndPrograms.csv")

In [2]:
df

,schoolyear,gradeLevel,classPeriod,classType,schoolName,gradePercentage,avid,sped,migrant,ell,student_ID
0,2024-2025,07,1,ELE,West Junior High,2000.0,Y,N,N,N,0HRJHI993
1,2024-2025,07,1,ELE,West Junior High,2000.0,N,N,N,N,CKN322II4
2,2024-2025,07,1,ELE,West Junior High,1950.0,N,N,N,N,V523OZUH8
3,2024-2025,07,1,ELE,West Junior High,1850.0,Y,N,N,N,OJDYS3434
4,2024-2025,07,1,ELE,West Junior High,1500.0,N,N,Y,Y,49RSM3UF6
...,...,...,...,...,...,...,...,...,...,...,...
200989,2024-2025,06,1,ELE,West Junior High,0.0,Y,N,N,Y,Z6F0V9HT0
200990,2024-2025,07,3,ENG,Allfeather Middle School,0.0,Y,N,N,N,299MYV6HZ
200991,2024-2025,05,7,SOC,Grand River Elementary School,0.0,Y,N,N,N,2U5D84IZX
200992,2024-2025,04,8,SCI,Leafy Elementary School,0.0,N,N,Y,Y,RX0L0B18M
200993,2024-2025,07,2,SCI,East Junior High,0.0,N,N,N,Y,4CJ11SZT2

In [4]:
df.fillna(80)

,schoolyear,gradeLevel,classPeriod,classType,schoolName,gradePercentage,avid,sped,migrant,ell,student_ID
0,2024-2025,07,1,ELE,West Junior High,2000.0,Y,N,N,N,0HRJHI993
1,2024-2025,07,1,ELE,West Junior High,2000.0,N,N,N,N,CKN322II4
2,2024-2025,07,1,ELE,West Junior High,1950.0,N,N,N,N,V523OZUH8
3,2024-2025,07,1,ELE,West Junior High,1850.0,Y,N,N,N,OJDYS3434
4,2024-2025,07,1,ELE,West Junior High,1500.0,N,N,Y,Y,49RSM3UF6
...,...,...,...,...,...,...,...,...,...,...,...
200989,2024-2025,06,1,ELE,West Junior High,0.0,Y,N,N,Y,Z6F0V9HT0
200990,2024-2025,07,3,ENG,Allfeather Middle School,0.0,Y,N,N,N,299MYV6HZ
200991,2024-2025,05,7,SOC,Grand River Elementary School,0.0,Y,N,N,N,2U5D84IZX
200992,2024-2025,04,8,SCI,Leafy Elementary School,0.0,N,N,Y,Y,RX0L0B18M
200993,2024-2025,07,2,SCI,East Junior High,0.0,N,N,N,Y,4CJ11SZT2